"""
Country name and code mappings for geonames integration
Generated automatically - do not edit manually
"""

from rdflib import URIRef

# Country name to ISO 3166-1 alpha-2 code mapping
COUNTRY_NAME_TO_ISO = {
    "Afghanistan": "AF",
    "Albania": "AL",
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Czechia": "CZ",
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "East Timor": "TL",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "North Macedonia": "MK",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Qatar": "QA",
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
}

# ISO 3166-1 alpha-2 code to English country name mapping
COUNTRY_ISO_TO_EN_COUNTRY_NAME = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AR": "Argentina",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BN": "Brunei",
    "BO": "Bolivia",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CD": "Democratic Republic of the Congo",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Ivory Coast",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cape Verde",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FM": "Micronesia",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GH": "Ghana",
    "GM": "Gambia",
    "GN": "Guinea",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GT": "Guatemala",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MR": "Mauritania",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NE": "Niger",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SY": "Syria",
    "SZ": "Eswatini",
    "TD": "Chad",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Vatican City",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WS": "Samoa",
    "YE": "Yemen",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

# Country name to geonames URI mapping
COUNTRY_NAME_TO_GEONAMES_URI = {
    "Afghanistan": URIRef("https://sws.geonames.org/1149361/"),
    "Albania": URIRef("https://sws.geonames.org/783754/"),
    "Algeria": URIRef("https://sws.geonames.org/2589581/"),
    "Andorra": URIRef("https://sws.geonames.org/3041565/"),
    "Angola": URIRef("https://sws.geonames.org/3351879/"),
    "Antigua and Barbuda": URIRef("https://sws.geonames.org/3576396/"),
    "Argentina": URIRef("https://sws.geonames.org/3865483/"),
    "Armenia": URIRef("https://sws.geonames.org/174982/"),
    "Australia": URIRef("https://sws.geonames.org/2077456/"),
    "Austria": URIRef("https://sws.geonames.org/2782113/"),
    "Azerbaijan": URIRef("https://sws.geonames.org/587116/"),
    "Bahamas": URIRef("https://sws.geonames.org/3572887/"),
    "Bahrain": URIRef("https://sws.geonames.org/290291/"),
    "Bangladesh": URIRef("https://sws.geonames.org/1210997/"),
    "Barbados": URIRef("https://sws.geonames.org/3374084/"),
    "Belarus": URIRef("https://sws.geonames.org/630336/"),
    "Belgium": URIRef("https://sws.geonames.org/2802361/"),
    "Belize": URIRef("https://sws.geonames.org/3582678/"),
    "Benin": URIRef("https://sws.geonames.org/2395170/"),
    "Bhutan": URIRef("https://sws.geonames.org/1252634/"),
    "Bolivia": URIRef("https://sws.geonames.org/3923057/"),
    "Bosnia and Herzegovina": URIRef("https://sws.geonames.org/3277605/"),
    "Botswana": URIRef("https://sws.geonames.org/933860/"),
    "Brazil": URIRef("https://sws.geonames.org/3469034/"),
    "Brunei": URIRef("https://sws.geonames.org/1820814/"),
    "Bulgaria": URIRef("https://sws.geonames.org/732800/"),
    "Burkina Faso": URIRef("https://sws.geonames.org/2361809/"),
    "Burundi": URIRef("https://sws.geonames.org/433561/"),
    "Cambodia": URIRef("https://sws.geonames.org/1831722/"),
    "Cameroon": URIRef("https://sws.geonames.org/2233387/"),
    "Canada": URIRef("https://sws.geonames.org/6251999/"),
    "Cape Verde": URIRef("https://sws.geonames.org/3374766/"),
    "Central African Republic": URIRef("https://sws.geonames.org/239880/"),
    "Chad": URIRef("https://sws.geonames.org/2434508/"),
    "Chile": URIRef("https://sws.geonames.org/3895114/"),
    "China": URIRef("https://sws.geonames.org/1814991/"),
    "Colombia": URIRef("https://sws.geonames.org/3686110/"),
    "Comoros": URIRef("https://sws.geonames.org/921929/"),
    "Congo": URIRef("https://sws.geonames.org/2260494/"),
    "Costa Rica": URIRef("https://sws.geonames.org/3624060/"),
    "Croatia": URIRef("https://sws.geonames.org/3202326/"),
    "Cuba": URIRef("https://sws.geonames.org/3562981/"),
    "Cyprus": URIRef("https://sws.geonames.org/146669/"),
    "Czechia": URIRef("https://sws.geonames.org/3077311/"),
    "Democratic Republic of the Congo": URIRef("https://sws.geonames.org/203312/"),
    "Denmark": URIRef("https://sws.geonames.org/2623032/"),
    "Djibouti": URIRef("https://sws.geonames.org/223816/"),
    "Dominica": URIRef("https://sws.geonames.org/3575830/"),
    "Dominican Republic": URIRef("https://sws.geonames.org/3508796/"),
    "Ecuador": URIRef("https://sws.geonames.org/3658394/"),
    "Egypt": URIRef("https://sws.geonames.org/357994/"),
    "El Salvador": URIRef("https://sws.geonames.org/3585968/"),
    "Equatorial Guinea": URIRef("https://sws.geonames.org/2309096/"),
    "Eritrea": URIRef("https://sws.geonames.org/338010/"),
    "Estonia": URIRef("https://sws.geonames.org/453733/"),
    "Eswatini": URIRef("https://sws.geonames.org/934841/"),
    "Ethiopia": URIRef("https://sws.geonames.org/337996/"),
    "Fiji": URIRef("https://sws.geonames.org/2205218/"),
    "Finland": URIRef("https://sws.geonames.org/660013/"),
    "France": URIRef("https://sws.geonames.org/3017382/"),
    "Gabon": URIRef("https://sws.geonames.org/2400553/"),
    "Gambia": URIRef("https://sws.geonames.org/2413451/"),
    "Georgia": URIRef("https://sws.geonames.org/614540/"),
    "Germany": URIRef("https://sws.geonames.org/2921044/"),
    "Ghana": URIRef("https://sws.geonames.org/2300660/"),
    "Greece": URIRef("https://sws.geonames.org/390903/"),
    "Grenada": URIRef("https://sws.geonames.org/3580239/"),
    "Guatemala": URIRef("https://sws.geonames.org/3595528/"),
    "Guinea": URIRef("https://sws.geonames.org/2420477/"),
    "Guinea-Bissau": URIRef("https://sws.geonames.org/2372248/"),
    "Guyana": URIRef("https://sws.geonames.org/3378535/"),
    "Haiti": URIRef("https://sws.geonames.org/3723988/"),
    "Honduras": URIRef("https://sws.geonames.org/3608932/"),
    "Hungary": URIRef("https://sws.geonames.org/719819/"),
    "Iceland": URIRef("https://sws.geonames.org/2629691/"),
    "India": URIRef("https://sws.geonames.org/1269750/"),
    "Indonesia": URIRef("https://sws.geonames.org/1643084/"),
    "Iran": URIRef("https://sws.geonames.org/130758/"),
    "Iraq": URIRef("https://sws.geonames.org/99237/"),
    "Ireland": URIRef("https://sws.geonames.org/2963597/"),
    "Israel": URIRef("https://sws.geonames.org/294640/"),
    "Italy": URIRef("https://sws.geonames.org/3175395/"),
    "Ivory Coast": URIRef("https://sws.geonames.org/2287781/"),
    "Jamaica": URIRef("https://sws.geonames.org/3489940/"),
    "Japan": URIRef("https://sws.geonames.org/1861060/"),
    "Jordan": URIRef("https://sws.geonames.org/248816/"),
    "Kazakhstan": URIRef("https://sws.geonames.org/1522867/"),
    "Kenya": URIRef("https://sws.geonames.org/192950/"),
    "Kiribati": URIRef("https://sws.geonames.org/4030945/"),
    "Kuwait": URIRef("https://sws.geonames.org/285570/"),
    "Kyrgyzstan": URIRef("https://sws.geonames.org/1527747/"),
    "Laos": URIRef("https://sws.geonames.org/1655842/"),
    "Latvia": URIRef("https://sws.geonames.org/458258/"),
    "Lebanon": URIRef("https://sws.geonames.org/272103/"),
    "Lesotho": URIRef("https://sws.geonames.org/932692/"),
    "Liberia": URIRef("https://sws.geonames.org/2275384/"),
    "Libya": URIRef("https://sws.geonames.org/2215636/"),
    "Liechtenstein": URIRef("https://sws.geonames.org/3042058/"),
    "Lithuania": URIRef("https://sws.geonames.org/597427/"),
    "Luxembourg": URIRef("https://sws.geonames.org/2960313/"),
    "Madagascar": URIRef("https://sws.geonames.org/1062947/"),
    "Malawi": URIRef("https://sws.geonames.org/927384/"),
    "Malaysia": URIRef("https://sws.geonames.org/1733045/"),
    "Maldives": URIRef("https://sws.geonames.org/1282028/"),
    "Mali": URIRef("https://sws.geonames.org/2453866/"),
    "Malta": URIRef("https://sws.geonames.org/2562770/"),
    "Marshall Islands": URIRef("https://sws.geonames.org/2080185/"),
    "Mauritania": URIRef("https://sws.geonames.org/2378080/"),
    "Mauritius": URIRef("https://sws.geonames.org/934292/"),
    "Mexico": URIRef("https://sws.geonames.org/3996063/"),
    "Micronesia": URIRef("https://sws.geonames.org/2081918/"),
    "Moldova": URIRef("https://sws.geonames.org/617790/"),
    "Monaco": URIRef("https://sws.geonames.org/2993457/"),
    "Mongolia": URIRef("https://sws.geonames.org/2029969/"),
    "Montenegro": URIRef("https://sws.geonames.org/3194884/"),
    "Morocco": URIRef("https://sws.geonames.org/2542007/"),
    "Mozambique": URIRef("https://sws.geonames.org/1036973/"),
    "Myanmar": URIRef("https://sws.geonames.org/1327865/"),
    "Namibia": URIRef("https://sws.geonames.org/3355338/"),
    "Nauru": URIRef("https://sws.geonames.org/2110425/"),
    "Nepal": URIRef("https://sws.geonames.org/1282988/"),
    "Netherlands": URIRef("https://sws.geonames.org/2750405/"),
    "New Zealand": URIRef("https://sws.geonames.org/2186224/"),
    "Nicaragua": URIRef("https://sws.geonames.org/3617476/"),
    "Niger": URIRef("https://sws.geonames.org/2440476/"),
    "Nigeria": URIRef("https://sws.geonames.org/2328926/"),
    "North Korea": URIRef("https://sws.geonames.org/1873107/"),
    "North Macedonia": URIRef("https://sws.geonames.org/718075/"),
    "Norway": URIRef("https://sws.geonames.org/3144096/"),
    "Oman": URIRef("https://sws.geonames.org/286963/"),
    "Pakistan": URIRef("https://sws.geonames.org/1168579/"),
    "Palau": URIRef("https://sws.geonames.org/1559582/"),
    "Panama": URIRef("https://sws.geonames.org/3703430/"),
    "Papua New Guinea": URIRef("https://sws.geonames.org/2088628/"),
    "Paraguay": URIRef("https://sws.geonames.org/3437598/"),
    "Peru": URIRef("https://sws.geonames.org/3932488/"),
    "Philippines": URIRef("https://sws.geonames.org/1694008/"),
    "Poland": URIRef("https://sws.geonames.org/798544/"),
    "Portugal": URIRef("https://sws.geonames.org/2264397/"),
    "Qatar": URIRef("https://sws.geonames.org/289688/"),
    "Romania": URIRef("https://sws.geonames.org/798549/"),
    "Russia": URIRef("https://sws.geonames.org/2017370/"),
    "Rwanda": URIRef("https://sws.geonames.org/49518/"),
    "Saint Kitts and Nevis": URIRef("https://sws.geonames.org/3575174/"),
    "Saint Lucia": URIRef("https://sws.geonames.org/3576468/"),
    "Saint Vincent and the Grenadines": URIRef("https://sws.geonames.org/3577815/"),
    "Samoa": URIRef("https://sws.geonames.org/4034894/"),
    "San Marino": URIRef("https://sws.geonames.org/3168068/"),
    "Sao Tome and Principe": URIRef("https://sws.geonames.org/2410758/"),
    "Saudi Arabia": URIRef("https://sws.geonames.org/102358/"),
    "Senegal": URIRef("https://sws.geonames.org/2245662/"),
    "Serbia": URIRef("https://sws.geonames.org/6290252/"),
    "Seychelles": URIRef("https://sws.geonames.org/241170/"),
    "Sierra Leone": URIRef("https://sws.geonames.org/2403846/"),
    "Slovakia": URIRef("https://sws.geonames.org/3057568/"),
    "Slovenia": URIRef("https://sws.geonames.org/3190538/"),
    "Solomon Islands": URIRef("https://sws.geonames.org/2103350/"),
    "Somalia": URIRef("https://sws.geonames.org/51537/"),
    "South Africa": URIRef("https://sws.geonames.org/953987/"),
    "South Korea": URIRef("https://sws.geonames.org/1835841/"),
    "South Sudan": URIRef("https://sws.geonames.org/7909807/"),
    "Spain": URIRef("https://sws.geonames.org/2510769/"),
    "Sri Lanka": URIRef("https://sws.geonames.org/1227603/"),
    "Sudan": URIRef("https://sws.geonames.org/366755/"),
    "Suriname": URIRef("https://sws.geonames.org/3382998/"),
    "Sweden": URIRef("https://sws.geonames.org/2661886/"),
    "Switzerland": URIRef("https://sws.geonames.org/2658434/"),
    "Syria": URIRef("https://sws.geonames.org/163843/"),
    "Taiwan": URIRef("https://sws.geonames.org/1668284/"),
    "Tajikistan": URIRef("https://sws.geonames.org/1220409/"),
    "Tanzania": URIRef("https://sws.geonames.org/149590/"),
    "Thailand": URIRef("https://sws.geonames.org/1605651/"),
    "Timor-Leste": URIRef("https://sws.geonames.org/1966436/"),
    "Togo": URIRef("https://sws.geonames.org/2363686/"),
    "Tonga": URIRef("https://sws.geonames.org/4032283/"),
    "Trinidad and Tobago": URIRef("https://sws.geonames.org/3573591/"),
    "Tunisia": URIRef("https://sws.geonames.org/2464461/"),
    "Turkey": URIRef("https://sws.geonames.org/298795/"),
    "Turkmenistan": URIRef("https://sws.geonames.org/1218197/"),
    "Tuvalu": URIRef("https://sws.geonames.org/2110297/"),
    "Uganda": URIRef("https://sws.geonames.org/226074/"),
    "Ukraine": URIRef("https://sws.geonames.org/690791/"),
    "United Arab Emirates": URIRef("https://sws.geonames.org/290557/"),
    "United Kingdom": URIRef("https://sws.geonames.org/2635167/"),
    "United States": URIRef("https://sws.geonames.org/6252001/"),
    "Uruguay": URIRef("https://sws.geonames.org/3439705/"),
    "Uzbekistan": URIRef("https://sws.geonames.org/1512440/"),
    "Vanuatu": URIRef("https://sws.geonames.org/2134431/"),
    "Venezuela": URIRef("https://sws.geonames.org/3625428/"),
    "Vietnam": URIRef("https://sws.geonames.org/1562822/"),
    "Yemen": URIRef("https://sws.geonames.org/69543/"),
    "Zambia": URIRef("https://sws.geonames.org/895949/"),
    "Zimbabwe": URIRef("https://sws.geonames.org/878675/"),
}

# ISO country code to geonames URI mapping
COUNTRY_CODE_TO_GEONAMES_URI = {
    "AD": URIRef("https://sws.geonames.org/3041565/"),
    "AE": URIRef("https://sws.geonames.org/290557/"),
    "AF": URIRef("https://sws.geonames.org/1149361/"),
    "AG": URIRef("https://sws.geonames.org/3576396/"),
    "AI": URIRef("https://sws.geonames.org/3573511/"),
    "AL": URIRef("https://sws.geonames.org/783754/"),
    "AM": URIRef("https://sws.geonames.org/174982/"),
    "AO": URIRef("https://sws.geonames.org/3351879/"),
    "AR": URIRef("https://sws.geonames.org/3865483/"),
    "AS": URIRef("https://sws.geonames.org/5880801/"),
    "AT": URIRef("https://sws.geonames.org/2782113/"),
    "AU": URIRef("https://sws.geonames.org/2077456/"),
    "AX": URIRef("https://sws.geonames.org/661882/"),
    "AZ": URIRef("https://sws.geonames.org/587116/"),
    "BA": URIRef("https://sws.geonames.org/3277605/"),
    "BB": URIRef("https://sws.geonames.org/3374084/"),
    "BD": URIRef("https://sws.geonames.org/1210997/"),
    "BE": URIRef("https://sws.geonames.org/2802361/"),
    "BF": URIRef("https://sws.geonames.org/2361809/"),
    "BG": URIRef("https://sws.geonames.org/732800/"),
    "BH": URIRef("https://sws.geonames.org/290291/"),
    "BI": URIRef("https://sws.geonames.org/433561/"),
    "BJ": URIRef("https://sws.geonames.org/2395170/"),
    "BM": URIRef("https://sws.geonames.org/3573345/"),
    "BN": URIRef("https://sws.geonames.org/1820814/"),
    "BO": URIRef("https://sws.geonames.org/3923057/"),
    "BQ": URIRef("https://sws.geonames.org/7626844/"),
    "BR": URIRef("https://sws.geonames.org/3469034/"),
    "BS": URIRef("https://sws.geonames.org/3572887/"),
    "BT": URIRef("https://sws.geonames.org/1252634/"),
    "BW": URIRef("https://sws.geonames.org/933860/"),
    "BY": URIRef("https://sws.geonames.org/630336/"),
    "BZ": URIRef("https://sws.geonames.org/3582678/"),
    "CA": URIRef("https://sws.geonames.org/6251999/"),
    "CD": URIRef("https://sws.geonames.org/203312/"),
    "CF": URIRef("https://sws.geonames.org/239880/"),
    "CG": URIRef("https://sws.geonames.org/2260494/"),
    "CH": URIRef("https://sws.geonames.org/2658434/"),
    "CI": URIRef("https://sws.geonames.org/2287781/"),
    "CK": URIRef("https://sws.geonames.org/1899402/"),
    "CL": URIRef("https://sws.geonames.org/3895114/"),
    "CM": URIRef("https://sws.geonames.org/2233387/"),
    "CN": URIRef("https://sws.geonames.org/1814991/"),
    "CO": URIRef("https://sws.geonames.org/3686110/"),
    "CR": URIRef("https://sws.geonames.org/3624060/"),
    "CU": URIRef("https://sws.geonames.org/3562981/"),
    "CV": URIRef("https://sws.geonames.org/3374766/"),
    "CY": URIRef("https://sws.geonames.org/146669/"),
    "CZ": URIRef("https://sws.geonames.org/3077311/"),
    "DE": URIRef("https://sws.geonames.org/2921044/"),
    "DJ": URIRef("https://sws.geonames.org/223816/"),
    "DK": URIRef("https://sws.geonames.org/2623032/"),
    "DM": URIRef("https://sws.geonames.org/3575830/"),
    "DO": URIRef("https://sws.geonames.org/3508796/"),
    "DZ": URIRef("https://sws.geonames.org/2589581/"),
    "EC": URIRef("https://sws.geonames.org/3658394/"),
    "EE": URIRef("https://sws.geonames.org/453733/"),
    "EG": URIRef("https://sws.geonames.org/357994/"),
    "ER": URIRef("https://sws.geonames.org/338010/"),
    "ES": URIRef("https://sws.geonames.org/2510769/"),
    "ET": URIRef("https://sws.geonames.org/337996/"),
    "FI": URIRef("https://sws.geonames.org/660013/"),
    "FJ": URIRef("https://sws.geonames.org/2205218/"),
    "FM": URIRef("https://sws.geonames.org/2081918/"),
    "FO": URIRef("https://sws.geonames.org/2622320/"),
    "FR": URIRef("https://sws.geonames.org/3017382/"),
    "GA": URIRef("https://sws.geonames.org/2400553/"),
    "GB": URIRef("https://sws.geonames.org/2635167/"),
    "GD": URIRef("https://sws.geonames.org/3580239/"),
    "GE": URIRef("https://sws.geonames.org/614540/"),
    "GF": URIRef("https://sws.geonames.org/3381670/"),
    "GG": URIRef("https://sws.geonames.org/3042362/"),
    "GH": URIRef("https://sws.geonames.org/2300660/"),
    "GL": URIRef("https://sws.geonames.org/3425505/"),
    "GM": URIRef("https://sws.geonames.org/2413451/"),
    "GN": URIRef("https://sws.geonames.org/2420477/"),
    "GP": URIRef("https://sws.geonames.org/3579143/"),
    "GQ": URIRef("https://sws.geonames.org/2309096/"),
    "GR": URIRef("https://sws.geonames.org/390903/"),
    "GT": URIRef("https://sws.geonames.org/3595528/"),
    "GU": URIRef("https://sws.geonames.org/4043988/"),
    "GW": URIRef("https://sws.geonames.org/2372248/"),
    "GY": URIRef("https://sws.geonames.org/3378535/"),
    "HK": URIRef("https://sws.geonames.org/1819730/"),
    "HN": URIRef("https://sws.geonames.org/3608932/"),
    "HR": URIRef("https://sws.geonames.org/3202326/"),
    "HT": URIRef("https://sws.geonames.org/3723988/"),
    "HU": URIRef("https://sws.geonames.org/719819/"),
    "ID": URIRef("https://sws.geonames.org/1643084/"),
    "IE": URIRef("https://sws.geonames.org/2963597/"),
    "IL": URIRef("https://sws.geonames.org/294640/"),
    "IM": URIRef("https://sws.geonames.org/3042225/"),
    "IN": URIRef("https://sws.geonames.org/1269750/"),
    "IQ": URIRef("https://sws.geonames.org/99237/"),
    "IR": URIRef("https://sws.geonames.org/130758/"),
    "IS": URIRef("https://sws.geonames.org/2629691/"),
    "IT": URIRef("https://sws.geonames.org/3175395/"),
    "JE": URIRef("https://sws.geonames.org/3042142/"),
    "JM": URIRef("https://sws.geonames.org/3489940/"),
    "JO": URIRef("https://sws.geonames.org/248816/"),
    "JP": URIRef("https://sws.geonames.org/1861060/"),
    "KE": URIRef("https://sws.geonames.org/192950/"),
    "KG": URIRef("https://sws.geonames.org/1527747/"),
    "KH": URIRef("https://sws.geonames.org/1831722/"),
    "KI": URIRef("https://sws.geonames.org/4030945/"),
    "KM": URIRef("https://sws.geonames.org/921929/"),
    "KN": URIRef("https://sws.geonames.org/3575174/"),
    "KP": URIRef("https://sws.geonames.org/1873107/"),
    "KR": URIRef("https://sws.geonames.org/1835841/"),
    "KW": URIRef("https://sws.geonames.org/285570/"),
    "KY": URIRef("https://sws.geonames.org/3580718/"),
    "KZ": URIRef("https://sws.geonames.org/1522867/"),
    "LA": URIRef("https://sws.geonames.org/1655842/"),
    "LB": URIRef("https://sws.geonames.org/272103/"),
    "LC": URIRef("https://sws.geonames.org/3576468/"),
    "LI": URIRef("https://sws.geonames.org/3042058/"),
    "LK": URIRef("https://sws.geonames.org/1227603/"),
    "LR": URIRef("https://sws.geonames.org/2275384/"),
    "LS": URIRef("https://sws.geonames.org/932692/"),
    "LT": URIRef("https://sws.geonames.org/597427/"),
    "LU": URIRef("https://sws.geonames.org/2960313/"),
    "LV": URIRef("https://sws.geonames.org/458258/"),
    "LY": URIRef("https://sws.geonames.org/2215636/"),
    "MA": URIRef("https://sws.geonames.org/2542007/"),
    "MC": URIRef("https://sws.geonames.org/2993457/"),
    "MD": URIRef("https://sws.geonames.org/617790/"),
    "ME": URIRef("https://sws.geonames.org/3194884/"),
    "MG": URIRef("https://sws.geonames.org/1062947/"),
    "MH": URIRef("https://sws.geonames.org/2080185/"),
    "MK": URIRef("https://sws.geonames.org/718075/"),
    "ML": URIRef("https://sws.geonames.org/2453866/"),
    "MM": URIRef("https://sws.geonames.org/1327865/"),
    "MN": URIRef("https://sws.geonames.org/2029969/"),
    "MO": URIRef("https://sws.geonames.org/1821275/"),
    "MP": URIRef("https://sws.geonames.org/4041468/"),
    "MQ": URIRef("https://sws.geonames.org/3570311/"),
    "MR": URIRef("https://sws.geonames.org/2378080/"),
    "MS": URIRef("https://sws.geonames.org/3578097/"),
    "MT": URIRef("https://sws.geonames.org/2562770/"),
    "MU": URIRef("https://sws.geonames.org/934292/"),
    "MV": URIRef("https://sws.geonames.org/1282028/"),
    "MW": URIRef("https://sws.geonames.org/927384/"),
    "MX": URIRef("https://sws.geonames.org/3996063/"),
    "MY": URIRef("https://sws.geonames.org/1733045/"),
    "MZ": URIRef("https://sws.geonames.org/1036973/"),
    "NA": URIRef("https://sws.geonames.org/3355338/"),
    "NC": URIRef("https://sws.geonames.org/2139685/"),
    "NE": URIRef("https://sws.geonames.org/2440476/"),
    "NG": URIRef("https://sws.geonames.org/2328926/"),
    "NI": URIRef("https://sws.geonames.org/3617476/"),
    "NL": URIRef("https://sws.geonames.org/2750405/"),
    "NO": URIRef("https://sws.geonames.org/3144096/"),
    "NP": URIRef("https://sws.geonames.org/1282988/"),
    "NR": URIRef("https://sws.geonames.org/2110425/"),
    "NZ": URIRef("https://sws.geonames.org/2186224/"),
    "OM": URIRef("https://sws.geonames.org/286963/"),
    "PA": URIRef("https://sws.geonames.org/3703430/"),
    "PE": URIRef("https://sws.geonames.org/3932488/"),
    "PF": URIRef("https://sws.geonames.org/4030656/"),
    "PG": URIRef("https://sws.geonames.org/2088628/"),
    "PH": URIRef("https://sws.geonames.org/1694008/"),
    "PK": URIRef("https://sws.geonames.org/1168579/"),
    "PL": URIRef("https://sws.geonames.org/798544/"),
    "PM": URIRef("https://sws.geonames.org/3424932/"),
    "PR": URIRef("https://sws.geonames.org/4566966/"),
    "PS": URIRef("https://sws.geonames.org/6254930/"),
    "PT": URIRef("https://sws.geonames.org/2264397/"),
    "PW": URIRef("https://sws.geonames.org/1559582/"),
    "PY": URIRef("https://sws.geonames.org/3437598/"),
    "QA": URIRef("https://sws.geonames.org/289688/"),
    "RE": URIRef("https://sws.geonames.org/935317/"),
    "RO": URIRef("https://sws.geonames.org/798549/"),
    "RS": URIRef("https://sws.geonames.org/6290252/"),
    "RU": URIRef("https://sws.geonames.org/2017370/"),
    "RW": URIRef("https://sws.geonames.org/49518/"),
    "SA": URIRef("https://sws.geonames.org/102358/"),
    "SB": URIRef("https://sws.geonames.org/2103350/"),
    "SC": URIRef("https://sws.geonames.org/241170/"),
    "SD": URIRef("https://sws.geonames.org/366755/"),
    "SE": URIRef("https://sws.geonames.org/2661886/"),
    "SH": URIRef("https://sws.geonames.org/3370751/"),
    "SI": URIRef("https://sws.geonames.org/3190538/"),
    "SJ": URIRef("https://sws.geonames.org/607072/"),
    "SK": URIRef("https://sws.geonames.org/3057568/"),
    "SL": URIRef("https://sws.geonames.org/2403846/"),
    "SM": URIRef("https://sws.geonames.org/3168068/"),
    "SN": URIRef("https://sws.geonames.org/2245662/"),
    "SO": URIRef("https://sws.geonames.org/51537/"),
    "SR": URIRef("https://sws.geonames.org/3382998/"),
    "SS": URIRef("https://sws.geonames.org/7909807/"),
    "ST": URIRef("https://sws.geonames.org/2410758/"),
    "SV": URIRef("https://sws.geonames.org/3585968/"),
    "SY": URIRef("https://sws.geonames.org/163843/"),
    "SZ": URIRef("https://sws.geonames.org/934841/"),
    "TD": URIRef("https://sws.geonames.org/2434508/"),
    "TF": URIRef("https://sws.geonames.org/1546748/"),
    "TG": URIRef("https://sws.geonames.org/2363686/"),
    "TH": URIRef("https://sws.geonames.org/1605651/"),
    "TJ": URIRef("https://sws.geonames.org/1220409/"),
    "TK": URIRef("https://sws.geonames.org/4031074/"),
    "TL": URIRef("https://sws.geonames.org/1966436/"),
    "TM": URIRef("https://sws.geonames.org/1218197/"),
    "TN": URIRef("https://sws.geonames.org/2464461/"),
    "TO": URIRef("https://sws.geonames.org/4032283/"),
    "TR": URIRef("https://sws.geonames.org/298795/"),
    "TT": URIRef("https://sws.geonames.org/3573591/"),
    "TV": URIRef("https://sws.geonames.org/2110297/"),
    "TW": URIRef("https://sws.geonames.org/1668284/"),
    "TZ": URIRef("https://sws.geonames.org/149590/"),
    "UA": URIRef("https://sws.geonames.org/690791/"),
    "UG": URIRef("https://sws.geonames.org/226074/"),
    "UM": URIRef("https://sws.geonames.org/5854968/"),
    "US": URIRef("https://sws.geonames.org/6252001/"),
    "UY": URIRef("https://sws.geonames.org/3439705/"),
    "UZ": URIRef("https://sws.geonames.org/1512440/"),
    "VC": URIRef("https://sws.geonames.org/3577815/"),
    "VE": URIRef("https://sws.geonames.org/3625428/"),
    "VI": URIRef("https://sws.geonames.org/4796775/"),
    "VN": URIRef("https://sws.geonames.org/1562822/"),
    "VU": URIRef("https://sws.geonames.org/2134431/"),
    "WF": URIRef("https://sws.geonames.org/4034749/"),
    "WS": URIRef("https://sws.geonames.org/4034894/"),
    "XK": URIRef("https://sws.geonames.org/831053/"),
    "YE": URIRef("https://sws.geonames.org/69543/"),
    "YT": URIRef("https://sws.geonames.org/1024031/"),
    "ZA": URIRef("https://sws.geonames.org/953987/"),
    "ZM": URIRef("https://sws.geonames.org/895949/"),
    "ZW": URIRef("https://sws.geonames.org/878675/"),
}
