from rdflib import Graph, Namespace, URIRef, Literal

COUNTRY_NAME_TO_ISO = {
    # A
    "Afghanistan": "AF",
    "Albania": "AL", 
    "Algeria": "DZ",
    "Andorra": "AD",
    "Angola": "AO",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Australia": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    
    # B
    "Bahamas": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bhutan": "BT",
    "Bolivia": "BO",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Brazil": "BR",
    "Brunei": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burundi": "BI",
    
    # C
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde": "CV",
    "Central African Republic": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "Colombia": "CO",
    "Comoros": "KM",
    "Congo": "CG",
    "Costa Rica": "CR",
    "Croatia": "HR",
    "Cuba": "CU",
    "Cyprus": "CY",
    "Czech Republic": "CZ",
    "Czechia": "CZ",
    
    # D
    "Democratic Republic of the Congo": "CD",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    
    # E
    "East Timor": "TL",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini": "SZ",
    "Ethiopia": "ET",
    
    # F
    "Fiji": "FJ",
    "Finland": "FI",
    "France": "FR",
    
    # G
    "Gabon": "GA",
    "Gambia": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Greece": "GR",
    "Grenada": "GD",
    "Guatemala": "GT",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    
    # H
    "Haiti": "HT",
    "Honduras": "HN",
    "Hungary": "HU",
    
    # I
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast": "CI",
    
    # J
    "Jamaica": "JM",
    "Japan": "JP",
    "Jordan": "JO",
    
    # K
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    
    # L
    "Laos": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    
    # M
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands": "MH",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mexico": "MX",
    "Micronesia": "FM",
    "Moldova": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar": "MM",
    
    # N
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands": "NL",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger": "NE",
    "Nigeria": "NG",
    "North Korea": "KP",
    "North Macedonia": "MK",
    "Norway": "NO",
    
    # O
    "Oman": "OM",
    
    # P
    "Pakistan": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "Peru": "PE",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    
    # Q
    "Qatar": "QA",
    
    # R
    "Romania": "RO",
    "Russia": "RU",
    "Rwanda": "RW",
    
    # S
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Korea": "KR",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan": "SD",
    "Suriname": "SR",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syria": "SY",
    
    # T
    "Taiwan": "TW",
    "Tajikistan": "TJ",
    "Tanzania": "TZ",
    "Thailand": "TH",
    "Timor-Leste": "TL",
    "Togo": "TG",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Turkey": "TR",
    "Turkmenistan": "TM",
    "Tuvalu": "TV",
    
    # U
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates": "AE",
    "United Kingdom": "GB",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    
    # V
    "Vanuatu": "VU",
    "Vatican City": "VA",
    "Venezuela": "VE",
    "Vietnam": "VN",
    
    # Y
    "Yemen": "YE",
    
    # Z
    "Zambia": "ZM",
    "Zimbabwe": "ZW"
}

results = [{'countryCode': {'type': 'literal', 'value': 'AD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3041565/'}},
 {'countryCode': {'type': 'literal', 'value': 'AE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/290557/'}},
 {'countryCode': {'type': 'literal', 'value': 'AF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1149361/'}},
 {'countryCode': {'type': 'literal', 'value': 'AG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3576396/'}},
 {'countryCode': {'type': 'literal', 'value': 'AI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3573511/'}},
 {'countryCode': {'type': 'literal', 'value': 'AL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/783754/'}},
 {'countryCode': {'type': 'literal', 'value': 'AM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/174982/'}},
 {'countryCode': {'type': 'literal', 'value': 'AO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3351879/'}},
 {'countryCode': {'type': 'literal', 'value': 'AR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3865483/'}},
 {'countryCode': {'type': 'literal', 'value': 'AS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/5880801/'}},
 {'countryCode': {'type': 'literal', 'value': 'AT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2782113/'}},
 {'countryCode': {'type': 'literal', 'value': 'AU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2077456/'}},
 {'countryCode': {'type': 'literal', 'value': 'AX'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/661882/'}},
 {'countryCode': {'type': 'literal', 'value': 'AZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/587116/'}},
 {'countryCode': {'type': 'literal', 'value': 'BA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3277605/'}},
 {'countryCode': {'type': 'literal', 'value': 'BB'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3374084/'}},
 {'countryCode': {'type': 'literal', 'value': 'BD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1210997/'}},
 {'countryCode': {'type': 'literal', 'value': 'BE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2802361/'}},
 {'countryCode': {'type': 'literal', 'value': 'BF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2361809/'}},
 {'countryCode': {'type': 'literal', 'value': 'BG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/732800/'}},
 {'countryCode': {'type': 'literal', 'value': 'BH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/290291/'}},
 {'countryCode': {'type': 'literal', 'value': 'BI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/433561/'}},
 {'countryCode': {'type': 'literal', 'value': 'BJ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2395170/'}},
 {'countryCode': {'type': 'literal', 'value': 'BM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3573345/'}},
 {'countryCode': {'type': 'literal', 'value': 'BN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1820814/'}},
 {'countryCode': {'type': 'literal', 'value': 'BO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3923057/'}},
 {'countryCode': {'type': 'literal', 'value': 'BQ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/7626844/'}},
 {'countryCode': {'type': 'literal', 'value': 'BR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3469034/'}},
 {'countryCode': {'type': 'literal', 'value': 'BS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3572887/'}},
 {'countryCode': {'type': 'literal', 'value': 'BT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1252634/'}},
 {'countryCode': {'type': 'literal', 'value': 'BW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/933860/'}},
 {'countryCode': {'type': 'literal', 'value': 'BY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/630336/'}},
 {'countryCode': {'type': 'literal', 'value': 'BZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3582678/'}},
 {'countryCode': {'type': 'literal', 'value': 'CA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/6251999/'}},
 {'countryCode': {'type': 'literal', 'value': 'CD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/203312/'}},
 {'countryCode': {'type': 'literal', 'value': 'CF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/239880/'}},
 {'countryCode': {'type': 'literal', 'value': 'CG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2260494/'}},
 {'countryCode': {'type': 'literal', 'value': 'CH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2658434/'}},
 {'countryCode': {'type': 'literal', 'value': 'CI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2287781/'}},
 {'countryCode': {'type': 'literal', 'value': 'CK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1899402/'}},
 {'countryCode': {'type': 'literal', 'value': 'CL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3895114/'}},
 {'countryCode': {'type': 'literal', 'value': 'CM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2233387/'}},
 {'countryCode': {'type': 'literal', 'value': 'CN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1814991/'}},
 {'countryCode': {'type': 'literal', 'value': 'CO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3686110/'}},
 {'countryCode': {'type': 'literal', 'value': 'CR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3624060/'}},
 {'countryCode': {'type': 'literal', 'value': 'CU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3562981/'}},
 {'countryCode': {'type': 'literal', 'value': 'CV'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3374766/'}},
 {'countryCode': {'type': 'literal', 'value': 'CY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/146669/'}},
 {'countryCode': {'type': 'literal', 'value': 'CZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3077311/'}},
 {'countryCode': {'type': 'literal', 'value': 'DE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2921044/'}},
 {'countryCode': {'type': 'literal', 'value': 'DJ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/223816/'}},
 {'countryCode': {'type': 'literal', 'value': 'DK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2623032/'}},
 {'countryCode': {'type': 'literal', 'value': 'DM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3575830/'}},
 {'countryCode': {'type': 'literal', 'value': 'DO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3508796/'}},
 {'countryCode': {'type': 'literal', 'value': 'DZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2589581/'}},
 {'countryCode': {'type': 'literal', 'value': 'EC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3658394/'}},
 {'countryCode': {'type': 'literal', 'value': 'EE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/453733/'}},
 {'countryCode': {'type': 'literal', 'value': 'EG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/357994/'}},
 {'countryCode': {'type': 'literal', 'value': 'ER'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/338010/'}},
 {'countryCode': {'type': 'literal', 'value': 'ES'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2510769/'}},
 {'countryCode': {'type': 'literal', 'value': 'ET'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/337996/'}},
 {'countryCode': {'type': 'literal', 'value': 'FI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/660013/'}},
 {'countryCode': {'type': 'literal', 'value': 'FJ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2205218/'}},
 {'countryCode': {'type': 'literal', 'value': 'FM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2081918/'}},
 {'countryCode': {'type': 'literal', 'value': 'FO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2622320/'}},
 {'countryCode': {'type': 'literal', 'value': 'FR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3017382/'}},
 {'countryCode': {'type': 'literal', 'value': 'GA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2400553/'}},
 {'countryCode': {'type': 'literal', 'value': 'GB'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2635167/'}},
 {'countryCode': {'type': 'literal', 'value': 'GD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3580239/'}},
 {'countryCode': {'type': 'literal', 'value': 'GE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/614540/'}},
 {'countryCode': {'type': 'literal', 'value': 'GF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3381670/'}},
 {'countryCode': {'type': 'literal', 'value': 'GG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3042362/'}},
 {'countryCode': {'type': 'literal', 'value': 'GH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2300660/'}},
 {'countryCode': {'type': 'literal', 'value': 'GL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3425505/'}},
 {'countryCode': {'type': 'literal', 'value': 'GM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2413451/'}},
 {'countryCode': {'type': 'literal', 'value': 'GN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2420477/'}},
 {'countryCode': {'type': 'literal', 'value': 'GP'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3579143/'}},
 {'countryCode': {'type': 'literal', 'value': 'GQ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2309096/'}},
 {'countryCode': {'type': 'literal', 'value': 'GR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/390903/'}},
 {'countryCode': {'type': 'literal', 'value': 'GT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3595528/'}},
 {'countryCode': {'type': 'literal', 'value': 'GU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4043988/'}},
 {'countryCode': {'type': 'literal', 'value': 'GW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2372248/'}},
 {'countryCode': {'type': 'literal', 'value': 'GY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3378535/'}},
 {'countryCode': {'type': 'literal', 'value': 'HK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1819730/'}},
 {'countryCode': {'type': 'literal', 'value': 'HN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3608932/'}},
 {'countryCode': {'type': 'literal', 'value': 'HR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3202326/'}},
 {'countryCode': {'type': 'literal', 'value': 'HT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3723988/'}},
 {'countryCode': {'type': 'literal', 'value': 'HU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/719819/'}},
 {'countryCode': {'type': 'literal', 'value': 'ID'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1643084/'}},
 {'countryCode': {'type': 'literal', 'value': 'IE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2963597/'}},
 {'countryCode': {'type': 'literal', 'value': 'IL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/294640/'}},
 {'countryCode': {'type': 'literal', 'value': 'IM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3042225/'}},
 {'countryCode': {'type': 'literal', 'value': 'IN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1269750/'}},
 {'countryCode': {'type': 'literal', 'value': 'IQ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/99237/'}},
 {'countryCode': {'type': 'literal', 'value': 'IR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/130758/'}},
 {'countryCode': {'type': 'literal', 'value': 'IS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2629691/'}},
 {'countryCode': {'type': 'literal', 'value': 'IT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3175395/'}},
 {'countryCode': {'type': 'literal', 'value': 'JE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3042142/'}},
 {'countryCode': {'type': 'literal', 'value': 'JM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3489940/'}},
 {'countryCode': {'type': 'literal', 'value': 'JO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/248816/'}},
 {'countryCode': {'type': 'literal', 'value': 'JP'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1861060/'}},
 {'countryCode': {'type': 'literal', 'value': 'KE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/192950/'}},
 {'countryCode': {'type': 'literal', 'value': 'KG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1527747/'}},
 {'countryCode': {'type': 'literal', 'value': 'KH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1831722/'}},
 {'countryCode': {'type': 'literal', 'value': 'KI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4030945/'}},
 {'countryCode': {'type': 'literal', 'value': 'KM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/921929/'}},
 {'countryCode': {'type': 'literal', 'value': 'KN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3575174/'}},
 {'countryCode': {'type': 'literal', 'value': 'KP'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1873107/'}},
 {'countryCode': {'type': 'literal', 'value': 'KR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1835841/'}},
 {'countryCode': {'type': 'literal', 'value': 'KW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/285570/'}},
 {'countryCode': {'type': 'literal', 'value': 'KY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3580718/'}},
 {'countryCode': {'type': 'literal', 'value': 'KZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1522867/'}},
 {'countryCode': {'type': 'literal', 'value': 'LA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1655842/'}},
 {'countryCode': {'type': 'literal', 'value': 'LB'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/272103/'}},
 {'countryCode': {'type': 'literal', 'value': 'LC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3576468/'}},
 {'countryCode': {'type': 'literal', 'value': 'LI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3042058/'}},
 {'countryCode': {'type': 'literal', 'value': 'LK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1227603/'}},
 {'countryCode': {'type': 'literal', 'value': 'LR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2275384/'}},
 {'countryCode': {'type': 'literal', 'value': 'LS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/932692/'}},
 {'countryCode': {'type': 'literal', 'value': 'LT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/597427/'}},
 {'countryCode': {'type': 'literal', 'value': 'LU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2960313/'}},
 {'countryCode': {'type': 'literal', 'value': 'LV'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/458258/'}},
 {'countryCode': {'type': 'literal', 'value': 'LY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2215636/'}},
 {'countryCode': {'type': 'literal', 'value': 'MA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2542007/'}},
 {'countryCode': {'type': 'literal', 'value': 'MC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2993457/'}},
 {'countryCode': {'type': 'literal', 'value': 'MD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/617790/'}},
 {'countryCode': {'type': 'literal', 'value': 'ME'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3194884/'}},
 {'countryCode': {'type': 'literal', 'value': 'MG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1062947/'}},
 {'countryCode': {'type': 'literal', 'value': 'MH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2080185/'}},
 {'countryCode': {'type': 'literal', 'value': 'MK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/718075/'}},
 {'countryCode': {'type': 'literal', 'value': 'ML'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2453866/'}},
 {'countryCode': {'type': 'literal', 'value': 'MM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1327865/'}},
 {'countryCode': {'type': 'literal', 'value': 'MN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2029969/'}},
 {'countryCode': {'type': 'literal', 'value': 'MO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1821275/'}},
 {'countryCode': {'type': 'literal', 'value': 'MP'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4041468/'}},
 {'countryCode': {'type': 'literal', 'value': 'MQ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3570311/'}},
 {'countryCode': {'type': 'literal', 'value': 'MR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2378080/'}},
 {'countryCode': {'type': 'literal', 'value': 'MS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3578097/'}},
 {'countryCode': {'type': 'literal', 'value': 'MT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2562770/'}},
 {'countryCode': {'type': 'literal', 'value': 'MU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/934292/'}},
 {'countryCode': {'type': 'literal', 'value': 'MV'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1282028/'}},
 {'countryCode': {'type': 'literal', 'value': 'MW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/927384/'}},
 {'countryCode': {'type': 'literal', 'value': 'MX'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3996063/'}},
 {'countryCode': {'type': 'literal', 'value': 'MY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1733045/'}},
 {'countryCode': {'type': 'literal', 'value': 'MZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1036973/'}},
 {'countryCode': {'type': 'literal', 'value': 'NA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3355338/'}},
 {'countryCode': {'type': 'literal', 'value': 'NC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2139685/'}},
 {'countryCode': {'type': 'literal', 'value': 'NE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2440476/'}},
 {'countryCode': {'type': 'literal', 'value': 'NG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2328926/'}},
 {'countryCode': {'type': 'literal', 'value': 'NI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3617476/'}},
 {'countryCode': {'type': 'literal', 'value': 'NL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2750405/'}},
 {'countryCode': {'type': 'literal', 'value': 'NO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3144096/'}},
 {'countryCode': {'type': 'literal', 'value': 'NP'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1282988/'}},
 {'countryCode': {'type': 'literal', 'value': 'NR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2110425/'}},
 {'countryCode': {'type': 'literal', 'value': 'NZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2186224/'}},
 {'countryCode': {'type': 'literal', 'value': 'OM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/286963/'}},
 {'countryCode': {'type': 'literal', 'value': 'PA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3703430/'}},
 {'countryCode': {'type': 'literal', 'value': 'PE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3932488/'}},
 {'countryCode': {'type': 'literal', 'value': 'PF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4030656/'}},
 {'countryCode': {'type': 'literal', 'value': 'PG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2088628/'}},
 {'countryCode': {'type': 'literal', 'value': 'PH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1694008/'}},
 {'countryCode': {'type': 'literal', 'value': 'PK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1168579/'}},
 {'countryCode': {'type': 'literal', 'value': 'PL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/798544/'}},
 {'countryCode': {'type': 'literal', 'value': 'PM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3424932/'}},
 {'countryCode': {'type': 'literal', 'value': 'PR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4566966/'}},
 {'countryCode': {'type': 'literal', 'value': 'PS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/6254930/'}},
 {'countryCode': {'type': 'literal', 'value': 'PT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2264397/'}},
 {'countryCode': {'type': 'literal', 'value': 'PW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1559582/'}},
 {'countryCode': {'type': 'literal', 'value': 'PY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3437598/'}},
 {'countryCode': {'type': 'literal', 'value': 'QA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/289688/'}},
 {'countryCode': {'type': 'literal', 'value': 'RE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/935317/'}},
 {'countryCode': {'type': 'literal', 'value': 'RO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/798549/'}},
 {'countryCode': {'type': 'literal', 'value': 'RS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/6290252/'}},
 {'countryCode': {'type': 'literal', 'value': 'RU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2017370/'}},
 {'countryCode': {'type': 'literal', 'value': 'RW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/49518/'}},
 {'countryCode': {'type': 'literal', 'value': 'SA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/102358/'}},
 {'countryCode': {'type': 'literal', 'value': 'SB'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2103350/'}},
 {'countryCode': {'type': 'literal', 'value': 'SC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/241170/'}},
 {'countryCode': {'type': 'literal', 'value': 'SD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/366755/'}},
 {'countryCode': {'type': 'literal', 'value': 'SE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2661886/'}},
 {'countryCode': {'type': 'literal', 'value': 'SH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3370751/'}},
 {'countryCode': {'type': 'literal', 'value': 'SI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3190538/'}},
 {'countryCode': {'type': 'literal', 'value': 'SJ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/607072/'}},
 {'countryCode': {'type': 'literal', 'value': 'SK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3057568/'}},
 {'countryCode': {'type': 'literal', 'value': 'SL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2403846/'}},
 {'countryCode': {'type': 'literal', 'value': 'SM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3168068/'}},
 {'countryCode': {'type': 'literal', 'value': 'SN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2245662/'}},
 {'countryCode': {'type': 'literal', 'value': 'SO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/51537/'}},
 {'countryCode': {'type': 'literal', 'value': 'SR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3382998/'}},
 {'countryCode': {'type': 'literal', 'value': 'SS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/7909807/'}},
 {'countryCode': {'type': 'literal', 'value': 'ST'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2410758/'}},
 {'countryCode': {'type': 'literal', 'value': 'SV'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3585968/'}},
 {'countryCode': {'type': 'literal', 'value': 'SY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/163843/'}},
 {'countryCode': {'type': 'literal', 'value': 'SZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/934841/'}},
 {'countryCode': {'type': 'literal', 'value': 'TD'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2434508/'}},
 {'countryCode': {'type': 'literal', 'value': 'TF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1546748/'}},
 {'countryCode': {'type': 'literal', 'value': 'TG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2363686/'}},
 {'countryCode': {'type': 'literal', 'value': 'TH'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1605651/'}},
 {'countryCode': {'type': 'literal', 'value': 'TJ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1220409/'}},
 {'countryCode': {'type': 'literal', 'value': 'TK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4031074/'}},
 {'countryCode': {'type': 'literal', 'value': 'TL'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1966436/'}},
 {'countryCode': {'type': 'literal', 'value': 'TM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1218197/'}},
 {'countryCode': {'type': 'literal', 'value': 'TN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2464461/'}},
 {'countryCode': {'type': 'literal', 'value': 'TO'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4032283/'}},
 {'countryCode': {'type': 'literal', 'value': 'TR'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/298795/'}},
 {'countryCode': {'type': 'literal', 'value': 'TT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3573591/'}},
 {'countryCode': {'type': 'literal', 'value': 'TV'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2110297/'}},
 {'countryCode': {'type': 'literal', 'value': 'TW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1668284/'}},
 {'countryCode': {'type': 'literal', 'value': 'TZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/149590/'}},
 {'countryCode': {'type': 'literal', 'value': 'UA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/690791/'}},
 {'countryCode': {'type': 'literal', 'value': 'UG'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/226074/'}},
 {'countryCode': {'type': 'literal', 'value': 'UM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/5854968/'}},
 {'countryCode': {'type': 'literal', 'value': 'US'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/6252001/'}},
 {'countryCode': {'type': 'literal', 'value': 'UY'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3439705/'}},
 {'countryCode': {'type': 'literal', 'value': 'UZ'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1512440/'}},
 {'countryCode': {'type': 'literal', 'value': 'VC'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3577815/'}},
 {'countryCode': {'type': 'literal', 'value': 'VE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/3625428/'}},
 {'countryCode': {'type': 'literal', 'value': 'VI'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4796775/'}},
 {'countryCode': {'type': 'literal', 'value': 'VN'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1562822/'}},
 {'countryCode': {'type': 'literal', 'value': 'VU'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/2134431/'}},
 {'countryCode': {'type': 'literal', 'value': 'WF'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4034749/'}},
 {'countryCode': {'type': 'literal', 'value': 'WS'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/4034894/'}},
 {'countryCode': {'type': 'literal', 'value': 'XK'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/831053/'}},
 {'countryCode': {'type': 'literal', 'value': 'YE'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/69543/'}},
 {'countryCode': {'type': 'literal', 'value': 'YT'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/1024031/'}},
 {'countryCode': {'type': 'literal', 'value': 'ZA'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/953987/'}},
 {'countryCode': {'type': 'literal', 'value': 'ZM'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/895949/'}},
 {'countryCode': {'type': 'literal', 'value': 'ZW'},
  'countryURI': {'type': 'uri', 'value': 'https://sws.geonames.org/878675/'}}]



# Reverse mapping
iso_to_country_name = {iso_code: country_name for country_name, iso_code in COUNTRY_NAME_TO_ISO.items()}

# Build URI mappings from SPARQL results
country_name_to_uri = {}
country_code_to_uri = {}

for result in results:  # Your SPARQL results
    iso_code = result['countryCode']['value']
    country_uri_str = result['countryURI']['value']
    country_uri = URIRef(country_uri_str)
    
    # Add to code -> URI mapping
    country_code_to_uri[iso_code] = country_uri
    
    # Add to name -> URI mapping if we have the country name
    if iso_code in iso_to_country_name:
        country_name = iso_to_country_name[iso_code]
        country_name_to_uri[country_name] = country_uri

# Generate the Python file
output_file = "/Users/chris/climate-risk-rag-aws/layers/knowledge-graph-layer/python/utils/country_mappings.py"

with open(output_file, 'w') as f:
    f.write('"""\n')
    f.write('Country name and code mappings for geonames integration\n')
    f.write('Generated automatically - do not edit manually\n')
    f.write('"""\n\n')
    f.write('from rdflib import URIRef\n\n')
    
    # Write COUNTRY_NAME_TO_ISO
    f.write('# Country name to ISO 3166-1 alpha-2 code mapping\n')
    f.write('COUNTRY_NAME_TO_ISO = {\n')
    for name, code in sorted(COUNTRY_NAME_TO_ISO.items()):
        f.write(f'    "{name}": "{code}",\n')
    f.write('}\n\n')
    
    # Write COUNTRY_ISO_TO_EN_COUNTRY_NAME
    f.write('# ISO 3166-1 alpha-2 code to English country name mapping\n')
    f.write('COUNTRY_ISO_TO_EN_COUNTRY_NAME = {\n')
    for code, name in sorted(iso_to_country_name.items()):
        f.write(f'    "{code}": "{name}",\n')
    f.write('}\n\n')
    
    # Write COUNTRY_NAME_TO_GEONAMES_URI
    f.write('# Country name to geonames URI mapping\n')
    f.write('COUNTRY_NAME_TO_GEONAMES_URI = {\n')
    for name, uri in sorted(country_name_to_uri.items()):
        f.write(f'    "{name}": URIRef("{uri}"),\n')
    f.write('}\n\n')
    
    # Write COUNTRY_CODE_TO_GEONAMES_URI
    f.write('# ISO country code to geonames URI mapping\n')
    f.write('COUNTRY_CODE_TO_GEONAMES_URI = {\n')
    for code, uri in sorted(country_code_to_uri.items()):
        f.write(f'    "{code}": URIRef("{uri}"),\n')
    f.write('}\n')

print(f"Generated country mappings file: {output_file}")



